### ISSUE TITLE
Game logs flooded with "Error executing task on Client" (java.lang.IndexOutOfBoundsException)

### ISSUE THREAD

**Issue by fwfy** [MayaqqDev/Estrogen#119]
As described in the issue title, while playing on a multiplayer server and having the estrogen patch in my inventory, my game logs become flooded over time with the following stacktrace:

```[23:00:09] [Render thread/ERROR]: Error executing task on Client
java.lang.IndexOutOfBoundsException: null
        at io.netty.buffer.EmptyByteBuf.readByte(EmptyByteBuf.java:523) ~[netty-buffer-4.1.82.Final.jar:?]
        at net.minecraft.class_2540.readByte(class_2540.java:1303) ~[client-intermediary.jar:?]
        at net.minecraft.class_2540.method_10816(class_2540.java:530) ~[client-intermediary.jar:?]
        at net.minecraft.class_2718.<init>(class_2718.java:22) ~[client-intermediary.jar:?]
        at dev.mayaqq.estrogen.networking.messages.s2c.RemoveStatusEffectPacket$Handler.lambda$handle$0(RemoveStatusEffectPacket.java:48) ~[Estrogen-4.2.10+1.20.1-fabric.jar:?]
        at com.teamresourceful.resourcefullib.common.networking.fabric.FabricClientPacketHelper.lambda$clientOnlyRegister$0(FabricClientPacketHelper.java:19) ~[resourcefullib-fabric-1.20.1-2.1.25.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
        at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
        at net.minecraft.class_310.method_1523(class_310.java:1175) ~[client-intermediary.jar:?]
        at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
        at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) ~[fabric-loader-0.16.0.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.16.0.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.16.0.jar:?]
        at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) ~[NewLaunch.jar:?]
        at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) ~[NewLaunch.jar:?]
        at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
```

This is causing problems in diagnosing another - seemingly unrelated - game crash that occurs intermittently, because at some point my game logs stop writing to disk.

Let me know if you need more details!

**Comment by MayaqqDev** [comment]
wow, never got this before, can we get more details? like a full log, or at least modlist, minecraft version and loader?

**Comment by fwfy** [comment]
Apologies for the delay. I see a PR has been made that closes this issue - would you still like a sample of the game logs?

**Comment by MayaqqDev** [comment]
all good
