### ISSUE TITLE
[Bug][1.18.2] Placing down a centrifuge crashes the game

### ISSUE THREAD

**Issue by jobl0ck** [MayaqqDev/Estrogen#16]
When placing down a centrifuge with the following versions causes a crash:

Minecraft: 1.18.2 
Fabric: 0.14.22
Fabric Api: 0.76.0+1.18.2
Create Fabric: 0.5.1-c-build.1159+mc1.18.2
Create: Estrogen: 3.0.3+1.18.2
REI: 8.3.662+fabric

The issue occurs in any instance with the specified mod versions + required apis

The Trace of the crash is as follows:

```

[19:55:26] [Render thread/ERROR]:
 Reported exception thrown!
net.minecraft.class_148: Rendering Block Entity
	at net.minecraft.class_824.method_3554(class_824.java:105) ~[client-intermediary.jar:?]
	at net.minecraft.class_824.method_3555(class_824.java:73) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:1354) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1034) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:813) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1122) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:737) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:236) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) [fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.22.jar:?]
Caused by: java.lang.IllegalArgumentException: Sided fluid storage may only be queried for a server world.
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.0.1-jre.jar:?]
	at net.fabricmc.fabric.api.transfer.v1.fluid.FluidStorage.lambda$static$0(FluidStorage.java:134) ~[fabric-transfer-api-v1-1.6.4+f4563ac860-eee48ef1f660e426.jar:?]
	at net.fabricmc.fabric.impl.lookup.block.BlockApiLookupImpl.find(BlockApiLookupImpl.java:99) ~[fabric-api-lookup-api-v1-1.6.3+2373a54560-76c678829b83d51c.jar:?]
	at net.fabricmc.fabric.api.lookup.v1.block.BlockApiLookup.find(BlockApiLookup.java:169) ~[fabric-api-lookup-api-v1-1.6.3+2373a54560-76c678829b83d51c.jar:?]
	at dev.mayaqq.estrogen.registry.client.blockRenderers.centrifuge.CentrifugeRenderer.renderSafe(CentrifugeRenderer.java:35) ~[Estrogen-3.0.3+1.18.2.jar:?]
	at dev.mayaqq.estrogen.registry.client.blockRenderers.centrifuge.CentrifugeRenderer.renderSafe(CentrifugeRenderer.java:20) ~[Estrogen-3.0.3+1.18.2.jar:?]
	at com.simibubi.create.foundation.blockEntity.renderer.SafeBlockEntityRenderer.method_3569(SafeBlockEntityRenderer.java:16) ~[create-fabric-0.5.1-c-build.1159+mc1.18.2.jar:?]
	at net.minecraft.class_824.method_23079(class_824.java:84) ~[client-intermediary.jar:?]
	at net.minecraft.class_824.method_23081(class_824.java:73) ~[client-intermediary.jar:?]
	at net.minecraft.class_824.method_3554(class_824.java:98) ~[client-intermediary.jar:?]
	... 10 more

```

**Comment by MayaqqDev** [comment]
Fixed
