### ISSUE TITLE
I am sorry its bugging again and I dont know why maybe its some off my modpack mods caussing this issue [FORGE] 

### ISSUE THREAD

**Issue by Hamza95400** [MayaqqDev/Estrogen#84]
[2024-04-11-2.log](https://github.com/MayaqqDev/Estrogen/files/14947961/2024-04-11-2.log)

**Comment by Hamza95400** [comment]
- estrogen 4.2.3+1.20.1-forge
	- evilcraft 1.2.36
	- evilcraftcompat 1.2.36
	- expandability 9.0.0
	- explorerscompass 1.20.1-1.3.3-forge
	- explorify 1.3.0-mc1.20
	- fabric_api 0.92.0+1.11.3+1.20.1
	- fabric_api_base 0.4.31+ef105b4977
	- fabric_api_lookup_api_v1 1.6.36+67f9824077
	- fabric_biome_api_v1 13.0.13+dd0389a577
	- fabric_block_api_v1 1.0.11+0e6cb7f777
	- fabric_block_view_api_v2 1.0.1+0767707077
	- fabric_blockrenderlayer_v1 1.1.41+1d0da21e77
	- fabric_client_tags_api_v1 1.1.2+5d6761b877
	- fabric_command_api_v1 1.2.34+f71b366f77
	- fabric_command_api_v2 2.2.13+561530ec77
	- fabric_content_registries_v0 4.0.11+a670df1e77
	- fabric_convention_tags_v1 1.5.5+fa3d1c0177
	- fabric_data_attachment_api_v1 1.0.0+30ef839e77
	- fabric_data_generation_api_v1 12.3.4+369cb3a477
	- fabric_dimensions_v1 2.1.54+8005d10d77
	- fabric_entity_events_v1 1.6.0+6274ab9d77
	- fabric_events_interaction_v0 0.6.2+0d0bd5a777
	- fabric_game_rule_api_v1 1.0.40+683d4da877
	- fabric_item_api_v1 2.1.28+2272fc7f77
	- fabric_item_group_api_v1 4.0.12+c9161c2d77
	- fabric_key_binding_api_v1 1.0.37+561530ec77
	- fabric_lifecycle_events_v1 2.2.22+afab492177
	- fabric_loot_api_v2 1.2.1+eb28f93e77
	- fabric_message_api_v1 5.1.9+52cc178c77
	- fabric_mining_level_api_v1 2.1.50+561530ec77
	- fabric_model_loading_api_v1 1.0.3+6274ab9d77
	- fabric_models_v0 0.4.2+7c3892a477
	- fabric_networking_api_v1 1.3.11+503a202477
	- fabric_object_builder_api_v1 11.1.3+2174fc8477
	- fabric_particles_v1 1.1.2+78e1ecb877
	- fabric_recipe_api_v1 1.0.21+514a076577
	- fabric_registry_sync_v0 2.3.3+1c0ea72177
	- fabric_renderer_api_v1 3.2.1+1d29b44577
	- fabric_renderer_indigo 1.5.1+67f9824077
	- fabric_rendering_data_attachment_v1 0.3.37+a6081afc77
	- fabric_rendering_fluids_v1 3.0.28+4ac5e37a77
	- fabric_rendering_v1 3.0.8+1c0ea72177
	- fabric_resource_conditions_api_v1 2.3.8+9ad825cd77
	- fabric_resource_loader_v0 0.11.10+cefbb70477
	- fabric_screen_api_v1 2.0.8+45a670a577
	- fabric_screen_handler_api_v1 1.3.30+561530ec77
	- fabric_sound_api_v1 1.0.13+4f23bd8477
	- fabric_transfer_api_v1 3.3.4+b00938ec77
	- fabric_transitive_access_wideners_v1 4.3.1+1880499877
	- farmersdelight 1.20.1-1.2.3
	- fastbench 8.0.2
	- felicity_craft 3.0.0
	- ferritecore 6.0.1
	- flightlib 2.0.3
	- flywheel 0.6.10-7
	- forge 47.2.8
	- forgeconfigapiport 8.0.0
	- fpsreducer 1.20-2.5
	- framedblocks 9.2.1
	- framework 0.6.26
	- fromtheshadows 1.592
	- fusion 1.0.6
	- galosphere 1.20.1-1.4.1
	- gateways 4.2.4
	- geckolib 4.2.3
	- goblintraders 1.9.2
	- grapplemod 1.20.1-v13
	- gravitation 1.1.4
	- hammerlib 20.1.22
	- handcrafted 3.0.5
	- harderspawners 46.25.1
	- harvestwithease 7.0.0.2
	- heracles 1.0.5
	- hermes 1.2.0
	- iceandfire 2.1.13-1.20.1-beta-4
	- idas 1.9.3+1.20.1
	- immediatelyfast 1.2.10+1.20.4
	- improvableskills 20.1.6
	- infernalmobs 1.20.1.0
	- infinitybuttons 1.20.1-4.0.2
	- integrated_api 1.5.1+1.20.1-forge
	- inventorio 1.10.1
	- inventorytotem 3.1
	- irons_spellbooks 1.20.1-1.2.1
	- itemfilters 2001.1.0-build.55
	- itemproductionlib 1.0.1
	- jade 11.6.3
	- jei 15.2.0.27
	- jeresources 1.4.0.247
	- journeymap 5.9.18
	- jukeboxfix 1.0.0+1.20.1
	- justenoughprofessions 3.0.1
	- kiwi 11.5.5
	- konkrete 1.6.1
	- kotlinforforge 4.10.0
	- kurosarchive2 2.2.0
	- lost_aether_content 1.2.3
	- luphieclutteredmod 2.1
	- majruszlibrary 7.0.5
	- majruszsdifficulty 1.9.8
	- mastersword 1.20.1-1.1.9.1
	- maxhealthfix 12.0.2
	- mcwbridges 2.1.0
	- mcwpaths 1.0.4
	- mdg 1.20.1
	- medieval_paintings 7.0
	- meisterous 1.0.0
	- metalsmeltingplus 1.0.0
	- minecells 1.7.1
	- minecraft 1.20.1
	- mixinextras 0.2.0
	- mixinsquared 0.1.1
	- modernfix 5.14.0+mc1.20.1
	- modmenu 7.2.2
	- modonomicon 1.39.0
	- momentariycore2 5.3.1
	- moonlight 1.20-2.10.10
	- more_music_discs 4.0.0
	- morediscs 1.20.1-32-forge
	- mousetweaks 2.25
	- mr_dungeons_andtaverns 3.0.3
	- multipiston 1.20-1.2.32-ALPHA
	- mutantmonsters 8.0.7
	- naturescompass 1.20.1-1.11.2-forge
	- neruina 1.3.0
	- netherdungeons 1.1.0-alpha2
	- nitrogen_internals 1.20.1-1.0.7-neoforge
	- obscure_api 15
	- oculus 1.6.15a
	- omega_config 1.2.3-1.18.1
	- omniscient_reader_weapons 1.0.0
	- orcz 0.82
	- outer_end 1.0.0
	- owo 0.11.21.20
	- paraglider 20.1.3
	- patchouli 1.20.1-81-FORGE
	- placebo 8.6.1
	- playeranimator 1.0.2-rc1+1.20
	- polymorph 0.49.2+1.20.1
	- puzzlesaccessapi 8.0.7
	- puzzleslib 8.1.13
	- quark 4.0-438
	- reach_entity_attributes 2.4.0
	- rechiseled 1.1.5c
	- rechiseledcreate 1.0.1
	- recipes_for_create 0.6.0
	- redeco 1.6.0
	- reeses_sodium_options 1.0.4
	- regions_unexplored 0.5.3
	- resourcefulconfig 2.1.2
	- resourcefullib 2.1.23
	- rpgsmw 7.91.20.1
	- rubidium 0.7.1
	- sawmill 1.20-1.2.6
	- scena 1.0.103
	- searchables 1.0.1
	- shrink 1.4.5
	- sight 1.2.2
	- simplyswords 1.52.0-1.20.1
	- skilltree 0.6.10a
	- smartbrainlib 1.12
	- sons_of_sins 2.1.6
	- sophisticatedbackpacks 3.20.1.1012
	- sophisticatedcore 0.6.3.553
	- sophisticatedstorage 0.9.5.716
	- sound_physics_remastered 1.20.1-1.2.1
	- spectrelib 0.13.15+1.20.1
	- spyglass_of_curios 1.7.2
	- stalwart_dungeons 1.2.8
	- structure_gel 2.16.0
	- structureessentials 1.20.1-3.2
	- structurize 1.20.1-1.0.633-BETA
	- superiorstructures 1.0.0
	- supermartijn642configlib 1.1.8
	- supermartijn642corelib 1.1.15
	- supplementaries 1.20-2.8.6
	- suppsquared 1.20-1.1.14
	- teamlapenlib 1.10.6
	- terrablender 3.0.0.169
	- textrues_embeddium_options 0.1.5+mc1.20.1
	- tflostblocks 1.20.1-1.5.0
	- tfmg 0.8.0b
	- thaumia 0.7.5
	- the_bumblezone 7.2.10+1.20.1-forge
	- theurgy 1.7.1
	- tombstone 8.6.4
	- toms_storage 1.6.5
	- totkcraftores 1.0.0
	- totw_modded 1.0.3-1.20.1
	- towerofgod 1.20.1-1.7.1.2
	- trashslot 15.1.0
	- treeharvester 8.3
	- twigs 1.20.1-3.1.1
	- twilightforest 4.3.2145
	- untamedwilds 4.0.3
	- uwa_undertale_tunes 1.0.0
	- valoria 1.20.1-build-0.5.2.1_b
	- vampirism 1.10.6
	- vampirism_integrations 1.8.0
	- veinmining 1.2.1+1.20.1
	- vintageimprovements 1.20.1-0.1.3.3
	- waystones 14.1.0
	- werewolves 1.2.0.1
	- worldedit 7.2.15+6463-5ca4dff
	- zelda_craft 1.8
	- zeldamod 1.0.0
	- zeta 1.0-14
	- zume 0.18.0
[15:53:54] [main/WARN]: Reference map 'Aquamirae.refmap.json' for aquamirae.mixins.json could not be read. If this is a development environment you can ignore this message
[15:53:54] [main/WARN]: Reference map 'grapplemod.refmap.json' for grapplemod.mixins.json could not be read. If this is a development environment you can ignore this message
[15:53:54] [main/INFO]: OptiFine was NOT detected.
[15:53:54] [main/INFO]: OptiFabric was NOT detected.
[15:53:54] [main/WARN]: Reference map 'suppsquared-common-refmap.json' for suppsquared-common.mixins.json could not be read. If this is a development environment you can ignore this message
[15:53:54] [main/WARN]: Reference map 'suppsquared-forge-refmap.json' for suppsquared.mixins.json could not be read. If this is a development environment you can ignore this message
[15:53:54] [main/WARN]: Reference map 'CreateHaven.refmap.json' for create_haven.mixins.json could not be read. If this is a development environment you can ignore this message
[15:53:54] [main/WARN]: Reference map 'trashslot.refmap.json' for trashslot.mixins.json could not be read. If this is a development environment you can ignore this message
[15:53:54] [main/WARN]: Reference map 'tfmg.refmap.json' for tfmg.mixins.json could not be read. If this is a development environment you can ignore this message
[15:53:54] [main/WARN]: Reference map 'simplyswords-forge-refmap.json' for simplyswords.mixins.json could not be read. If this is a development environment you can ignore this message
[15:53:55] [main/WARN]: Reference map 'modonomicon.refmap.json' for modonomicon.mixins.json could not be read. If this is a development environment you can ignore this message
[15:53:55] [main/WARN]: Reference map 'modonomicon.refmap.json' for modonomicon.forge.mixins.json could not be read. If this is a development environment you can ignore this message
[15:53:55] [main/WARN]: Reference map 'chiselsandbits.refmap.json' for chisels-and-bits.mixins.json could not be read. If this is a development environment you can ignore this message
[15:53:57] [main/INFO]: Patching IForgeItemStack#getEnchantmentLevel
[15:53:57] [main/INFO]: Patching IForgeItemStack#getEnchantmentLevel
[15:53:57] [main/WARN]: Error loading class: dev/latvian/mods/kubejs/recipe/RecipesEventJS (java.lang.ClassNotFoundException: dev.latvian.mods.kubejs.recipe.RecipesEventJS)
[15:53:57] [main/WARN]: @Mixin target dev.latvian.mods.kubejs.recipe.RecipesEventJS was not found mixins.hammerlib.json:bs.kubejs.RecipeEventJSMixin from mod hammerlib
[15:53:58] [main/INFO]: Replaced 2 calls to Enchantment#getMaxLevel() in net/minecraft/world/inventory/AnvilMenu
[15:53:58] [main/INFO]: Patching IForgeItemStack#getEnchantmentLevel
[15:53:58] [main/INFO]: Patching IForgeItemStack#getEnchantmentLevel
[15:53:58] [main/WARN]: Error loading class: com/hollingsworth/arsnouveau/common/items/SpellCrossbow (java.lang.ClassNotFoundException: com.hollingsworth.arsnouveau.common.items.SpellCrossbow)
[15:54:01] [main/INFO]: Patching FishingHook#catchingFish
[15:54:02] [main/WARN]: Error loading class: tfar/davespotioneering/blockentity/AdvancedBrewingStandBlockEntity (java.lang.ClassNotFoundException: tfar.davespotioneering.blockentity.AdvancedBrewingStandBlockEntity)
[15:54:02] [main/WARN]: @Mixin target tfar.davespotioneering.blockentity.AdvancedBrewingStandBlockEntity was not found itemproductionlib.mixins.json:davespotioneering/AdvancedBrewingStandBlockEntityMixin from mod itemproductionlib
[15:54:03] [main/WARN]: Error loading class: com/aetherteam/aether_genesis/block/natural/GreenAercloudBlock (java.lang.ClassNotFoundException: com.aetherteam.aether_genesis.block.natural.GreenAercloudBlock)
[15:54:03] [main/WARN]: @Mixin target com.aetherteam.aether_genesis.block.natural.GreenAercloudBlock was not found aether_redux.mixins.json:common.block.GreenAercloudBlockMixin from mod aether_redux
[15:54:03] [main/WARN]: Error loading class: com/aetherteam/aether_genesis/block/natural/PurpleAercloudBlock (java.lang.ClassNotFoundException: com.aetherteam.aether_genesis.block.natural.PurpleAercloudBlock)
[15:54:03] [main/WARN]: @Mixin target com.aetherteam.aether_genesis.block.natural.PurpleAercloudBlock was not found aether_redux.mixins.json:common.block.PurpleAercloudBlockMixin from mod aether_redux
[15:54:03] [main/WARN]: Error loading class: com/aetherteam/aether_genesis/client/renderer/entity/SkyrootMimicRenderer (java.lang.ClassNotFoundException: com.aetherteam.aether_genesis.client.renderer.entity.SkyrootMimicRenderer)
[15:54:03] [main/WARN]: @Mixin target com.aetherteam.aether_genesis.client.renderer.entity.SkyrootMimicRenderer was not found aether_redux.mixins.json:client.render.MimicRendererMixin from mod aether_redux
[15:54:03] [main/WARN]: Error loading class: net/builderdog/ancient_aether/client/renderer/entity/renderer/FestiveSwetRenderer (java.lang.ClassNotFoundException: net.builderdog.ancient_aether.client.renderer.entity.renderer.FestiveSwetRenderer)
[15:54:03] [main/WARN]: @Mixin target net.builderdog.ancient_aether.client.renderer.entity.renderer.FestiveSwetRenderer was not found aether_redux.mixins.json:client.render.SwetRendererMixin from mod aether_redux
[15:54:03] [main/WARN]: Error loading class: dev/emi/emi/screen/EmiScreenManager (java.lang.ClassNotFoundException: dev.emi.emi.screen.EmiScreenManager)
[15:54:03] [main/WARN]: Error loading class: me/shedaniel/rei/impl/client/gui/ScreenOverlayImpl (java.lang.ClassNotFoundException: me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl)
[15:54:03] [main/INFO]: Loaded config for: structureessentials.json
[15:54:03] [main/INFO]: bre2el.fpsreducer.mixin.RenderSystemMixin will be applied.
[15:54:03] [main/INFO]: bre2el.fpsreducer.mixin.WindowMixin will NOT be applied because OptiFine was NOT detected.
[15:54:04] [main/WARN]: Error loading class: me/jellysquid/mods/lithium/common/ai/pathing/PathNodeDefaults (java.lang.ClassNotFoundException: me.jellysquid.mods.lithium.common.ai.pathing.PathNodeDefaults)
[15:54:04] [main/INFO]: Replaced 2 calls to Enchantment#getMaxLevel() in net/minecraft/world/item/CreativeModeTabs
[15:54:05] [main/INFO]: Instancing error handler class com.illusivesoulworks.polymorph.mixin.IntegratedMixinPlugin
[15:54:05] [main/FATAL]: Mixin prepare for mod estrogen failed preparing client.ConfigValueMixin in estrogen-common.mixins.json: org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException Critical problem: estrogen-common.mixins.json:client.ConfigValueMixin from mod estrogen target net.minecraftforge.common.ForgeConfigSpec$ConfigValue was loaded too early.
org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException: Critical problem: estrogen-common.mixins.json:client.ConfigValueMixin from mod estrogen target net.minecraftforge.common.ForgeConfigSpec$ConfigValue was loaded too early.
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readDeclaredTargets(MixinInfo.java:948) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:882) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:852) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:781) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:540) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-10.0.9.jar:10.0.9+10.0.9+main.dcd20f30]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at dev.su5ed.sinytra.connector.service.ConnectorLoaderService$1.lambda$updateModuleReads$0(ConnectorLoaderService.java:60) ~[Connector-1.0.0-beta.40+1.20.1.jar%23421!/:1.0.0-beta.40+1.20.1]
	at cpw.mods.modlauncher.api.LamdbaExceptionUtils.uncheck(LamdbaExceptionUtils.java:95) ~[modlauncher-10.0.9.jar%2390!/:10.0.9+10.0.9+main.dcd20f30]
	at dev.su5ed.sinytra.connector.service.ConnectorLoaderService$1.updateModuleReads(ConnectorLoaderService.java:60) ~[Connector-1.0.0-beta.40+1.20.1.jar%23421!/:1.0.0-beta.40+1.20.1]
	at net.minecraftforge.fml.loading.ImmediateWindowHandler.acceptGameLayer(ImmediateWindowHandler.java:71) ~[fmlloader-1.20.1-47.2.8.jar:1.0]
	at net.minecraftforge.fml.loading.FMLLoader.beforeStart(FMLLoader.java:207) ~[fmlloader-1.20.1-47.2.8.jar:1.0]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.launchService(CommonLaunchHandler.java:92) ~[fmlloader-1.20.1-47.2.8.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]

**Comment by MayaqqDev** [comment]
Why do I have a feeling this is caused by connector...

**Comment by MayaqqDev** [comment]
Can you try temporarily removing it please? Just so I can debug easier

**Comment by Hamza95400** [comment]
OK I will try

**Comment by Hamza95400** [comment]
so when i remouve sinytra my modpack doesnt work , so i tried in a nother one with estrogen and sinytra and everything work properly

**Comment by MayaqqDev** [comment]
Fixed next release.

**Comment by Hamza95400** [comment]
so I updated almost every mod in my modpack and it work now so

**Comment by MayaqqDev** [comment]
Awesome!
